name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use the appropriate Node.js version

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install Dependencies
        run: npm install

      - name: Build the Ionic app
        run: ionic build --prod # Build the app using Ionic CLI

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The default output directory for Ionic
